spring:
  datasource:
    url: jdbc:mysql://${host}:4000/test?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2,TLSv1.3
    username: ${user}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver